version: '2.0'
services: 
    hub:
        build:
          context: .
          dockerfile: Dockerfile.jupyterhub
        container_name: jupyterhub
        ports: 
            - "8000:8000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
            # Bind docker volume on host for jupyterHub
            - "data:${DATA_VOLUME_CONTAINER}"
        environment: 
            # All containers will joing this network
            # All containers will join this network
            DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
            # JupyterHub will spawn this Notebook image for users
            DOCKER_NOTEBOOK_IMAGE: ${LOCAL_NOTEBOOK_IMAGE}
            # Notebook directory inside user image
            DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
            # Using this run command (optional)
            DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
        # command: >
        #   jupyterhub -f /srv/jupyterhub/jupyterhub_config.py


volumes:
  data:
    external:
      name: ${DATA_VOLUME_HOST}

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}